### ISSUE TITLE
How we can pass cancellation token to controller to cancel long running process.

### ISSUE THREAD

**Issue by CodeguruEdison** [DataBooster/DbWebApi#3]
How we can pass cancellation token to controller to cancel long running process.

**Comment by AbelCheng** [comment]
Thank you so much, this suggestion is really helpful.

For the present, asynchronous methods have not yet been implemented from the lowest level, cancellation token can't be passed into existing synchronous methods. So the whole implementation stack will need to be enhanced, this may involve the lowest level [DataBooster Library](https://databooster.codeplex.com/) to be split into two versions: *one for .Net 4.0* and *another for .Net 4.5 (ADO.NET4.5 supports asynchronous methods)*. It will take a while.

To work around around this limitation at the moment, you may:
- Let the client side to use asynchronous call with cancellation token.   
For the server side, leave it as is, this is completely rely on IIS thread pooling.
- Or, Wrap the synchronous method in a Task.Run(...) as a fake async task.

However neither of above two work-arounds can actually cancel a long running process in the database session.

**Comment by safarigps** [comment]
Thank you. do you have any plan to integrate this feature in near future?

**Comment by AbelCheng** [comment]
Yes, it's in the to-do-list.
