### ISSUE TITLE
.Net Client hangs on ayns/await

### ISSUE THREAD

**Issue by safarigps** [DataBooster/DbWebApi#4]
Hi ,

I found  clients hangs on with out ConfigureAwait(false). Once i add this(ConfigureAwait(false), it works fine. thought , it will help full to you to modify the code.

Thanks
Sam

#if WEB_API2
		protected async Task<T> ExecAsAsync<T>(string requestUri, IDictionary<string, object> inputParameters, CancellationToken cancellationToken) where T : class
		{
			HttpResponseMessage httpResponse = await ExecRawAsync(requestUri, inputParameters, cancellationToken).ConfigureAwait(false);
			return httpResponse.ReadAs<T>();
		}
#else

**Comment by AbelCheng** [comment]
Sorry for late reply, I will look into this and get back to you later.

**Comment by AbelCheng** [comment]
Thanks a lot for fixing it. The fix has been released in the nuget package 1.1.8 - http://www.nuget.org/packages/DataBooster.DbWebApi.Client.Net/1.1.8 now.
